### ISSUE TITLE
Use dashed lines to distinguish cuts/folds

### ISSUE THREAD

**Issue by AnmAtAnm** [fenichel/mask-pattern-generator#11]
Use dashed lines to highlight fold lines in pattern, such as:
 * The tab at the ears.
 * The nose and chin darts.

Use a fold indicator (arrows pointed at edge) for the front fold of the mask (nose to chin).

![Example fold indicator](https://doitbetteryourself.club/wp-content/uploads/2017/02/Foldline-2.jpg)

Also see "What Is A Fold Line On A Sewing Pattern?" on [this page](https://www.thecreativecurator.com/how-to-read-sewing-patterns/)

**Comment by fenichel** [comment]
I added a dashed line for the tab--the nose and throat sections are actual cut lines so I'm leaving them as-is.


Place on fold is next.

**Comment by fenichel** [comment]
Added cut on fold.

**Comment by AnmAtAnm** [comment]
Why "Cut on fold" instead of "Place on fold"? It isn't a cut, is it?

**Comment by fenichel** [comment]
I'm used to cut on fold. But totally okay with changing the text to "Place on fold"
