### ISSUE TITLE
Measure ear-to-ear

### ISSUE THREAD

**Issue by AnmAtAnm** [fenichel/mask-pattern-generator#13]
Currently, the app requests "Throat to ear bottom (E to F)" measurement, or "The front of your throat to the bottom of your ear." in the instructions.

I believe this could be measured ear-to-ear, with the app using half the inputed value. Measuring the full length avoids guessing the height at which the mask might sit on the throat. It allows the user to feel the difference of mask tautness with an open and closed jaw as they measure a comfortable length.

**Comment by fenichel** [comment]
Sounds reasonable. Can you do test measurements and/or builds with a few people to see if it gives a good result?

**Comment by fenichel** [comment]
Closing because I removed this measurement, but we can reopen if needed.
